"""empty message

Revision ID: 3c08d86c702d
Revises: df4e04401798
Create Date: 2022-02-08 12:52:04.259492

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c08d86c702d'
down_revision = 'df4e04401798'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('cart_items_shopping_cart_id_fkey', 'cart_items', type_='foreignkey')
    op.create_foreign_key(None, 'cart_items', 'shopping_carts', ['shopping_cart_id'], ['id'])
    op.drop_column('cart_items', 'quantity')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart_items', sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'cart_items', type_='foreignkey')
    op.create_foreign_key('cart_items_shopping_cart_id_fkey', 'cart_items', 'users', ['shopping_cart_id'], ['id'])
    # ### end Alembic commands ###
